
server:
  port: 8080

spring:
  application:
    name: notificacion de envios
  logging:
    level:
      root: INFO
      reactor:
        netty: OFF
  r2dbc:
    scripts:
      schema: classpath:schema.sql
    url: r2dbc:pool:postgresql://localhost:5432/delivery
    username: postgres
    password: tu_contraseña_de_base_de_datos
    #pool:
     # initial-size: 5
     # max-size: 20
     # max-idle-time: 5m
  mail:
    host: smtp.gmail.com
    port: 587
    username: tu_correo_de_gmail@gmail.com
    password: tu_contraseña_de_aplicación_de_16_dígitos
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  webflux:
    problemdetails:
      enabled: true

management:
  endpoint:
    health:
      enabled: true
      show-details: never
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health, liveness, readiness
      base-path: /
      path-mapping:
        health: health
        liveness: liveness
        readiness: readiness

weather:
  key: 8tu_api_key_weatherapi
  server: https://api.weatherapi.com
  uri: /v1/forecast.json?key=%s&q=%s,%s&days=2&aqi=no&alerts=no&lang=es

logging:
  level:
    com:
      shipment:
      notification:
        logger: INFO

springdoc:
  swagger-ui:
    path: /docs/swagger.html
